# Generated by Django 5.1 on 2024-11-09 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Incharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('number', models.PositiveBigIntegerField()),
                ('photo', models.FileField(upload_to='')),
                ('gender', models.CharField(max_length=10)),
                ('dob', models.DateField()),
                ('email', models.EmailField(max_length=50)),
                ('place', models.CharField(max_length=50)),
                ('post', models.CharField(max_length=50)),
                ('pin', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='InventoryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='InventoryManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('number', models.PositiveBigIntegerField()),
                ('photo', models.FileField(upload_to='')),
                ('gender', models.CharField(max_length=10)),
                ('dob', models.DateField()),
                ('email', models.EmailField(max_length=50)),
                ('place', models.CharField(max_length=50)),
                ('post', models.CharField(max_length=50)),
                ('pin', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.PositiveIntegerField()),
                ('capacity', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ward_number', models.PositiveIntegerField()),
                ('capacity', models.PositiveIntegerField()),
                ('photo', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('quantity', models.PositiveIntegerField()),
                ('date', models.DateField(auto_now_add=True)),
                ('photo', models.FileField(blank=True, null=True, upload_to='')),
                ('CATEGORY', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.inventorycategory')),
                ('ADDED_BY', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.inventorymanager')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(default='pending', max_length=30)),
                ('PRODUCT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.inventory')),
                ('SENDER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.incharge')),
            ],
        ),
        migrations.AddField(
            model_name='inventorymanager',
            name='LOGIN',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.login'),
        ),
        migrations.AddField(
            model_name='incharge',
            name='LOGIN',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.login'),
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone', models.PositiveBigIntegerField()),
                ('email', models.EmailField(max_length=40)),
                ('place', models.CharField(max_length=40)),
                ('post', models.CharField(max_length=40)),
                ('pin', models.PositiveIntegerField()),
                ('photo', models.FileField(upload_to='')),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.login')),
            ],
        ),
    ]
