# Generated by Django 5.1 on 2024-11-10 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='WARD',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='MyApp.ward'),
            preserve_default=False,
        ),
    ]
