# Generated by Django 5.1 on 2024-11-10 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0002_room_ward'),
    ]

    operations = [
        migrations.AddField(
            model_name='incharge',
            name='WARD',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='MyApp.ward'),
            preserve_default=False,
        ),
    ]
