# Generated by Django 5.1 on 2024-11-17 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0003_incharge_ward'),
    ]

    operations = [
        migrations.AddField(
            model_name='ward',
            name='details',
            field=models.CharField(default='sample', max_length=500),
            preserve_default=False,
        ),
    ]
