# Generated by Django 5.1 on 2024-11-17 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0004_ward_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ward',
            name='ward_number',
            field=models.CharField(max_length=50),
        ),
    ]
