# Generated by Django 5.1 on 2024-11-18 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0006_room_details_room_image_room_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='status',
            field=models.CharField(default='Available', max_length=20),
            preserve_default=False,
        ),
    ]
