# Generated by Django 5.1 on 2024-11-19 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0007_room_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('number', models.PositiveBigIntegerField()),
                ('photo', models.FileField(upload_to='')),
                ('gender', models.CharField(max_length=10)),
                ('dob', models.DateField()),
                ('email', models.EmailField(max_length=50)),
                ('place', models.CharField(max_length=50)),
                ('post', models.CharField(max_length=50)),
                ('qualification', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=50)),
                ('pin', models.PositiveIntegerField()),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.login')),
            ],
        ),
    ]
