# Generated by Django 5.1 on 2024-11-20 01:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0008_doctor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(default='Admitted', max_length=30)),
                ('ddate', models.DateField(auto_now_add=True)),
                ('name', models.CharField(max_length=50)),
                ('number', models.PositiveBigIntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('dob', models.DateField()),
                ('address', models.CharField(max_length=50)),
                ('DOCTOR', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.doctor')),
            ],
        ),
    ]
