# Generated by Django 5.1 on 2024-11-20 01:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0009_patients'),
    ]

    operations = [
        migrations.AddField(
            model_name='patients',
            name='ROOM',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='MyApp.room'),
            preserve_default=False,
        ),
    ]
