# Generated by Django 5.1 on 2024-11-20 01:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0010_patients_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patients',
            name='address',
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name='PatientsDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('pstatus', models.TextField()),
                ('plan', models.TextField()),
                ('medicines', models.TextField()),
                ('status', models.CharField(max_length=20)),
                ('PATIENT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.patients')),
            ],
        ),
    ]
