# Generated by Django 5.1 on 2024-11-20 03:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0011_alter_patients_address_patientsdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('PRODUCT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.inventory')),
                ('WARD', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.ward')),
            ],
        ),
    ]
