# Generated by Django 5.1 on 2024-11-20 03:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0012_inventorystock'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('date', models.DateField()),
                ('PATIENT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.patients')),
                ('PRODUCT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.inventory')),
            ],
        ),
    ]
