# Generated by Django 5.1.3 on 2025-01-07 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0013_inventoryallocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryallocation',
            name='quantity',
            field=models.PositiveBigIntegerField(),
        ),
    ]
