# Generated by Django 5.2.3 on 2025-06-13 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0014_alter_inventoryallocation_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patients',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='patients',
            name='ddate',
            field=models.DateField(),
        ),
    ]
