# Generated by Django 5.2.3 on 2025-06-13 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0015_alter_patients_date_alter_patients_ddate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patients',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='patients',
            name='ddate',
            field=models.DateField(auto_now_add=True),
        ),
    ]
