# Generated by Django 5.2.3 on 2025-06-17 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0016_alter_patients_date_alter_patients_ddate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ward',
            name='photo',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
